# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass, replace
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
    final,
)


class CancelIntent:
    pass


@final
@dataclass(frozen=True)
class NoCancel(CancelIntent):
    pass


@final
@dataclass(frozen=True)
class Cancelled(CancelIntent):
    pass


CancelIntentT = NoCancel | Cancelled


class ReturnedKind:
    pass


@final
@dataclass(frozen=True)
class RetNormal(ReturnedKind):
    pass


@final
@dataclass(frozen=True)
class RetCancelled(ReturnedKind):
    pass


ReturnedKindT = RetNormal | RetCancelled


class State:
    pass


@final
@dataclass(frozen=True)
class Initial(State):
    pass


@final
@dataclass(frozen=True)
class Pending(State):
    arg0: CancelIntent


@final
@dataclass(frozen=True)
class Returned(State):
    arg0: ReturnedKind


StateT = Initial | Pending | Returned


initial_state: State = Initial()


pending_fresh: State = Pending(NoCancel())


pending_cancelled: State = Pending(Cancelled())


returned_normal: State = Returned(RetNormal())


returned_cancelled: State = Returned(RetCancelled())


class Event:
    pass


@final
@dataclass(frozen=True)
class Prompt(Event):
    pass


@final
@dataclass(frozen=True)
class CancelFire(Event):
    pass


@final
@dataclass(frozen=True)
class SubprocessExit(Event):
    pass


@final
@dataclass(frozen=True)
class Recover(Event):
    pass


@final
@dataclass(frozen=True)
class Return(Event):
    pass


EventT = Prompt | CancelFire | SubprocessExit | Recover | Return


def transition(
    current: State,
    event0: Event,
) -> State | None:
    match current:
        case Initial():
            match event0:
                case Prompt():
                    return Pending(NoCancel())
                case CancelFire():
                    return None
                case SubprocessExit():
                    return None
                case Recover():
                    return None
                case Return():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case Pending(ci):
            match ci:
                case NoCancel():
                    match event0:
                        case Prompt():
                            return None
                        case CancelFire():
                            return Pending(Cancelled())
                        case SubprocessExit():
                            return Pending(ci)
                        case Recover():
                            return Pending(ci)
                        case Return():
                            return Returned(RetNormal())
                        case __impossible:
                            assert_never(__impossible)
                case Cancelled():
                    match event0:
                        case Prompt():
                            return None
                        case CancelFire():
                            return Pending(Cancelled())
                        case SubprocessExit():
                            return Pending(ci)
                        case Recover():
                            return Pending(ci)
                        case Return():
                            return Returned(RetCancelled())
                        case __impossible:
                            assert_never(__impossible)
                case __impossible:
                    assert_never(__impossible)
        case Returned(r):
            return None
        case __impossible:
            assert_never(__impossible)
