# Generated by rocq-python-extraction (target: Python 3.14t)  # From coord_index.v:1:0
from itertools import islice  # From coord_index.v:1:0
from dataclasses import dataclass  # From coord_index.v:1:0
from fractions import Fraction  # From coord_index.v:1:0
from typing import (
    Any,
    Awaitable,
    Callable,
    Generic,
    Iterable,
    Iterator,
    Never,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)  # From coord_index.v:1:0

_CoForceT = TypeVar("_CoForceT")  # From coord_index.v:1:0
_ModuleArgT = TypeVar("_ModuleArgT")  # From coord_index.v:1:0
_ModuleRetT = TypeVar("_ModuleRetT")  # From coord_index.v:1:0
_StateTState = TypeVar("_StateTState")  # From coord_index.v:1:0
_StateTValue = TypeVar("_StateTValue")  # From coord_index.v:1:0
_StateTNext = TypeVar("_StateTNext")  # From coord_index.v:1:0
_IOValue = TypeVar("_IOValue")  # From coord_index.v:1:0
_IONext = TypeVar("_IONext")  # From coord_index.v:1:0


class _Impossible(RuntimeError):  # From coord_index.v:1:0
    pass  # From coord_index.v:1:0


def _impossible() -> Never:  # From coord_index.v:1:0
    raise _Impossible()  # From coord_index.v:1:0


class _RocqUtf8BoundaryError(UnicodeError):  # From coord_index.v:1:0
    pass  # From coord_index.v:1:0


class _RocqNumericDomainError(ValueError):  # From coord_index.v:1:0
    pass  # From coord_index.v:1:0


def _rocq_numeric_domain_error(
    kind: str, value: object
) -> Never:  # From coord_index.v:1:0
    raise _RocqNumericDomainError(
        f"Rocq {kind} value out of domain: {value!r}"
    )  # From coord_index.v:1:0


key = int  # finite-map module key alias  # From coord_index.v:1:0
elt = int  # finite-set module element alias  # From coord_index.v:1:0


def _rocq_positive_key(key: int) -> int:  # From coord_index.v:1:0
    if key <= 0:  # From coord_index.v:1:0
        raise _RocqNumericDomainError(
            f"positive map/set key", key
        )  # From coord_index.v:1:0
    return key  # From coord_index.v:1:0


def _rocq_string_key(key: str) -> str:  # From coord_index.v:1:0
    if not isinstance(key, str):  # From coord_index.v:1:0
        raise TypeError(
            f"Rocq string map/set key must be str: {key!r}"
        )  # From coord_index.v:1:0
    return key  # From coord_index.v:1:0


def _rocq_sorted_key(key: object) -> Any:  # From coord_index.v:1:0
    return (
        key.encode("utf-8") if isinstance(key, str) else key
    )  # From coord_index.v:1:0


def _rocq_map_add(
    key: object, value: object, mapping: dict[object, object]
) -> dict[object, object]:  # From coord_index.v:1:0
    result = dict(mapping)  # From coord_index.v:1:0
    result[key] = value  # From coord_index.v:1:0
    return result  # From coord_index.v:1:0


def _rocq_map_remove(
    key: object, mapping: dict[object, object]
) -> dict[object, object]:  # From coord_index.v:1:0
    result = dict(mapping)  # From coord_index.v:1:0
    result.pop(key, None)  # From coord_index.v:1:0
    return result  # From coord_index.v:1:0


def _rocq_map_elements(
    mapping: dict[object, object],
) -> list[tuple[object, object]]:  # From coord_index.v:1:0
    return sorted(
        mapping.items(), key=lambda item: _rocq_sorted_key(item[0])
    )  # From coord_index.v:1:0


def _rocq_map_fold(
    function: Callable[[object, object, object], object],
    mapping: dict[object, object],
    initial: object,
) -> object:  # From coord_index.v:1:0
    result = initial  # From coord_index.v:1:0
    for key, value in _rocq_map_elements(mapping):  # From coord_index.v:1:0
        result = function(key, value, result)  # From coord_index.v:1:0
    return result  # From coord_index.v:1:0


def _rocq_set_add(
    key: object, values: frozenset[object]
) -> frozenset[object]:  # From coord_index.v:1:0
    return frozenset((*values, key))  # From coord_index.v:1:0


def _rocq_set_remove(
    key: object, values: frozenset[object]
) -> frozenset[object]:  # From coord_index.v:1:0
    return frozenset(
        value for value in values if value != key
    )  # From coord_index.v:1:0


def _rocq_set_elements(
    values: frozenset[object],
) -> list[object]:  # From coord_index.v:1:0
    return sorted(values, key=_rocq_sorted_key)  # From coord_index.v:1:0


def _rocq_set_fold(
    function: Callable[[object, object], object],
    values: frozenset[object],
    initial: object,
) -> object:  # From coord_index.v:1:0
    result = initial  # From coord_index.v:1:0
    for value in _rocq_set_elements(values):  # From coord_index.v:1:0
        result = function(value, result)  # From coord_index.v:1:0
    return result  # From coord_index.v:1:0


def _rocq_string_cons(head: int, tail: str) -> str:  # From coord_index.v:1:0
    try:  # From coord_index.v:1:0
        return bytes([head]).decode("utf-8") + tail  # From coord_index.v:1:0
    except UnicodeDecodeError as exc:  # From coord_index.v:1:0
        raise _RocqUtf8BoundaryError(
            "Rocq string split crosses a UTF-8 boundary"
        ) from exc  # From coord_index.v:1:0


def _rocq_string_uncons(value: str) -> tuple[int, str]:  # From coord_index.v:1:0
    encoded = value.encode("utf-8")  # From coord_index.v:1:0
    if not encoded:  # From coord_index.v:1:0
        raise _Impossible()  # From coord_index.v:1:0
    try:  # From coord_index.v:1:0
        tail = encoded[1:].decode("utf-8")  # From coord_index.v:1:0
    except UnicodeDecodeError as exc:  # From coord_index.v:1:0
        raise _RocqUtf8BoundaryError(
            "Rocq string split crosses a UTF-8 boundary"
        ) from exc  # From coord_index.v:1:0
    return encoded[0], tail  # From coord_index.v:1:0


def _rocq_ascii_to_int(
    b0: bool, b1: bool, b2: bool, b3: bool, b4: bool, b5: bool, b6: bool, b7: bool
) -> int:  # From coord_index.v:1:0
    return sum(
        (1 << i) for i, bit in enumerate((b0, b1, b2, b3, b4, b5, b6, b7)) if bit
    )  # From coord_index.v:1:0


def _rocq_ascii_bits(
    value: int,
) -> tuple[bool, bool, bool, bool, bool, bool, bool, bool]:  # From coord_index.v:1:0
    if value < 0 or value > 255:  # From coord_index.v:1:0
        raise ValueError("Rocq byte/ascii value out of range")  # From coord_index.v:1:0
    return cast(
        tuple[bool, bool, bool, bool, bool, bool, bool, bool],
        tuple(bool(value & (1 << i)) for i in range(8)),
    )  # From coord_index.v:1:0


class StateT(Generic[_StateTState, _StateTValue]):  # From coord_index.v:1:0
    def __init__(
        self,
        step: Callable[[_StateTState], tuple[_StateTValue, _StateTState]],
        state: _StateTState | None = None,
    ) -> None:  # From coord_index.v:1:0
        self._step = step  # From coord_index.v:1:0
        self.state = state  # From coord_index.v:1:0

    def run(self, state: _StateTState) -> _StateTValue:  # From coord_index.v:1:0
        value, next_state = self._step(state)  # From coord_index.v:1:0
        self.state = next_state  # From coord_index.v:1:0
        return value  # From coord_index.v:1:0

    def run_with_state(
        self, state: _StateTState
    ) -> tuple[_StateTValue, _StateTState]:  # From coord_index.v:1:0
        result = self._step(state)  # From coord_index.v:1:0
        self.state = result[1]  # From coord_index.v:1:0
        return result  # From coord_index.v:1:0

    def bind(
        self, f: Callable[[_StateTValue], StateT[_StateTState, _StateTNext]]
    ) -> StateT[_StateTState, _StateTNext]:  # From coord_index.v:1:0
        def run_bound(
            state: _StateTState,
        ) -> tuple[_StateTNext, _StateTState]:  # From coord_index.v:1:0
            value, next_state = self._step(state)  # From coord_index.v:1:0
            return f(value).run_with_state(next_state)  # From coord_index.v:1:0

        return StateT(run_bound, self.state)  # From coord_index.v:1:0

    @classmethod  # From coord_index.v:1:0
    def pure(
        cls, value: _StateTValue
    ) -> StateT[_StateTState, _StateTValue]:  # From coord_index.v:1:0
        return StateT(lambda state: (value, state))  # From coord_index.v:1:0

    @classmethod  # From coord_index.v:1:0
    def get_state(cls) -> StateT[_StateTState, _StateTState]:  # From coord_index.v:1:0
        return StateT(lambda state: (state, state))  # From coord_index.v:1:0

    @classmethod  # From coord_index.v:1:0
    def put_state(
        cls, new_state: _StateTState
    ) -> StateT[_StateTState, None]:  # From coord_index.v:1:0
        return StateT(lambda _state: (None, new_state))  # From coord_index.v:1:0


class IO(Generic[_IOValue]):  # From coord_index.v:1:0
    def __init__(
        self, thunk: Callable[[], Awaitable[_IOValue]]
    ) -> None:  # From coord_index.v:1:0
        self._thunk = thunk  # From coord_index.v:1:0

    async def run(self) -> _IOValue:  # From coord_index.v:1:0
        return await self._thunk()  # From coord_index.v:1:0

    def bind(
        self, f: Callable[[_IOValue], IO[_IONext]]
    ) -> IO[_IONext]:  # From coord_index.v:1:0
        async def run_bound() -> _IONext:  # From coord_index.v:1:0
            value = await self.run()  # From coord_index.v:1:0
            return await f(value).run()  # From coord_index.v:1:0

        return IO(run_bound)  # From coord_index.v:1:0

    @classmethod  # From coord_index.v:1:0
    def pure(cls, value: _IOValue) -> IO[_IOValue]:  # From coord_index.v:1:0
        async def run_pure() -> _IOValue:  # From coord_index.v:1:0
            return value  # From coord_index.v:1:0

        return IO(run_pure)  # From coord_index.v:1:0


def coforce(value: Callable[[], _CoForceT]) -> _CoForceT:  # From coord_index.v:1:0
    return value()  # From coord_index.v:1:0


def coprefix_eq(
    n: int, left: Iterable[object], right: Iterable[object]
) -> bool:  # From coord_index.v:1:0
    return tuple(islice(iter(left), n)) == tuple(
        islice(iter(right), n)
    )  # From coord_index.v:1:0


def coprefix_hash(n: int, value: Iterable[object]) -> int:  # From coord_index.v:1:0
    return hash(tuple(islice(iter(value), n)))  # From coord_index.v:1:0


class __ModuleNamespace:  # From coord_index.v:1:0
    pass  # From coord_index.v:1:0


def __apply_applicative(
    cache: dict[int, _ModuleRetT],
    build: Callable[[_ModuleArgT], _ModuleRetT],
    arg: _ModuleArgT,
) -> _ModuleRetT:  # From coord_index.v:1:0
    key = id(arg)  # From coord_index.v:1:0
    cached = cache.get(key)  # From coord_index.v:1:0
    if cached is None:  # From coord_index.v:1:0
        cached = build(arg)  # From coord_index.v:1:0
        cache[key] = cached  # From coord_index.v:1:0
    return cached  # From coord_index.v:1:0


__ = None  # erased logical argument  # From coord_index.v:1:0
# bool: remapped to Python primitive  # From coord_index.v:1:0

# nat: remapped to Python primitive  # From coord_index.v:1:0

_A = TypeVar("_A")  # From coord_index.v:1:0

# option: remapped to Python primitive  # From coord_index.v:1:0

_A = TypeVar("_A")  # From coord_index.v:1:0
_B = TypeVar("_B")  # From coord_index.v:1:0

# prod: remapped to Python primitive  # From coord_index.v:1:0

_A = TypeVar("_A")  # From coord_index.v:1:0

# list: remapped to Python primitive  # From coord_index.v:1:0

_LengthT0 = TypeVar("_LengthT0")  # From coord_index.v:1:0


def length(x: list[_LengthT0]) -> int:  # From coord_index.v:1:0
    def length(l):  # From coord_index.v:1:0
        return (
            lambda __list: (
                (lambda: 0)()
                if __list == []
                else (lambda a, l_: length(l_) + 1)(__list[0], __list[1:])
            )
        )(l)  # From coord_index.v:1:0

    return length(x)  # From coord_index.v:1:0


# positive: remapped to Python primitive  # From coord_index.v:1:0

# ascii: remapped to Python primitive  # From coord_index.v:1:0

# string: remapped to Python primitive  # From coord_index.v:1:0


def add_claim(
    thread: int, claims: frozenset[int]
) -> frozenset[int]:  # From coord_index.v:1:0
    return _rocq_set_add(_rocq_positive_key(thread), claims)  # From coord_index.v:1:0


def remove_claim(
    thread: int, claims: frozenset[int]
) -> frozenset[int]:  # From coord_index.v:1:0
    return _rocq_set_remove(
        _rocq_positive_key(thread), claims
    )  # From coord_index.v:1:0


def has_claim(claims: frozenset[int], thread: int) -> bool:  # From coord_index.v:1:0
    return _rocq_positive_key(thread) in claims  # From coord_index.v:1:0


def assign_issue(
    issue: int, owner: str, owners: dict[int, str]
) -> dict[int, str]:  # From coord_index.v:1:0
    return _rocq_map_add(
        _rocq_positive_key(issue), owner, owners
    )  # From coord_index.v:1:0


def unassign_issue(
    issue: int, owners: dict[int, str]
) -> dict[int, str]:  # From coord_index.v:1:0
    return _rocq_map_remove(_rocq_positive_key(issue), owners)  # From coord_index.v:1:0


def issue_owner(
    owners: dict[int, str], issue: int
) -> str | None:  # From coord_index.v:1:0
    return owners.get(_rocq_positive_key(issue))  # From coord_index.v:1:0


# Python ExtractionDiagnostic [PYEX003]: Type alias declaration is not emitted Remediation: Use a concrete inductive/record or add an extraction remapping for the type.  # From coord_index.v:1:0
def repo_provider(repo: repo_entry) -> str:  # From coord_index.v:1:0
    return (
        lambda __pair: (
            lambda s, p: (
                lambda __pair: (lambda s0, provider: provider)(__pair[0], __pair[1])
            )(p)
        )(__pair[0], __pair[1])
    )(repo)  # From coord_index.v:1:0


def repo_providers(repos: list[repo_entry]) -> list[str]:  # From coord_index.v:1:0
    return (
        lambda __list: (
            (lambda: [])()
            if __list == []
            else (lambda repo, rest: [repo_provider(repo)] + repo_providers(rest))(
                __list[0], __list[1:]
            )
        )
    )(repos)  # From coord_index.v:1:0


def repo_count(repos: list[repo_entry]) -> int:  # From coord_index.v:1:0
    return length(repos)  # From coord_index.v:1:0
