# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass, replace
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
    final,
)


class LegacyDemand:
    pass


@final
@dataclass(frozen=True)
class LegacyEmpty(LegacyDemand):
    pass


@final
@dataclass(frozen=True)
class LegacyNonEmpty(LegacyDemand):
    pass


LegacyDemandT = LegacyEmpty | LegacyNonEmpty


class DurableDemandState:
    pass


@final
@dataclass(frozen=True)
class DurableEmpty(DurableDemandState):
    pass


@final
@dataclass(frozen=True)
class DurableNonEmpty(DurableDemandState):
    pass


DurableDemandStateT = DurableEmpty | DurableNonEmpty


class ProviderInterrupt:
    pass


@final
@dataclass(frozen=True)
class InterruptNotRequested(ProviderInterrupt):
    pass


@final
@dataclass(frozen=True)
class InterruptWasRequested(ProviderInterrupt):
    pass


ProviderInterruptT = InterruptNotRequested | InterruptWasRequested


@final
@dataclass(frozen=True)
class State:
    legacy_demand: LegacyDemand
    durable_demand: DurableDemandState
    provider_interrupt: ProviderInterrupt


empty_state: State = State(
    legacy_demand=LegacyEmpty(),
    durable_demand=DurableEmpty(),
    provider_interrupt=InterruptNotRequested(),
)


legacy_state: State = State(
    legacy_demand=LegacyNonEmpty(),
    durable_demand=DurableEmpty(),
    provider_interrupt=InterruptNotRequested(),
)


durable_state: State = State(
    legacy_demand=LegacyEmpty(),
    durable_demand=DurableNonEmpty(),
    provider_interrupt=InterruptNotRequested(),
)


preempted_durable_state: State = State(
    legacy_demand=LegacyEmpty(),
    durable_demand=DurableNonEmpty(),
    provider_interrupt=InterruptWasRequested(),
)


mixed_state: State = State(
    legacy_demand=LegacyNonEmpty(),
    durable_demand=DurableNonEmpty(),
    provider_interrupt=InterruptWasRequested(),
)


class Event:
    pass


@final
@dataclass(frozen=True)
class WebhookArrives(Event):
    pass


@final
@dataclass(frozen=True)
class DurableDemandRecorded(Event):
    pass


@final
@dataclass(frozen=True)
class InterruptRequested(Event):
    pass


@final
@dataclass(frozen=True)
class HandlerDone(Event):
    pass


@final
@dataclass(frozen=True)
class DurableDemandDrained(Event):
    pass


@final
@dataclass(frozen=True)
class WorkerTurnStart(Event):
    pass


EventT = (
    WebhookArrives
    | DurableDemandRecorded
    | InterruptRequested
    | HandlerDone
    | DurableDemandDrained
    | WorkerTurnStart
)


def with_legacy(
    s: State,
    legacy: LegacyDemand,
) -> State:
    return replace(
        s,
        legacy_demand=legacy,
    )


def with_durable(
    s: State,
    durable: DurableDemandState,
) -> State:
    return replace(
        s,
        durable_demand=durable,
    )


def with_interrupt(
    s: State,
    interrupt: ProviderInterrupt,
) -> State:
    return replace(
        s,
        provider_interrupt=interrupt,
    )


def transition(
    current: State,
    event0: Event,
) -> State | None:
    match event0:
        case WebhookArrives():
            return with_legacy(current, LegacyNonEmpty())
        case DurableDemandRecorded():
            return with_durable(current, DurableNonEmpty())
        case InterruptRequested():
            match current.durable_demand:
                case DurableEmpty():
                    return None
                case DurableNonEmpty():
                    return with_interrupt(current, InterruptWasRequested())
                case __impossible:
                    assert_never(__impossible)
        case HandlerDone():
            match current.legacy_demand:
                case LegacyEmpty():
                    return None
                case LegacyNonEmpty():
                    return with_legacy(current, LegacyEmpty())
                case __impossible:
                    assert_never(__impossible)
        case DurableDemandDrained():
            match current.durable_demand:
                case DurableEmpty():
                    return None
                case DurableNonEmpty():
                    return with_durable(current, DurableEmpty())
                case __impossible:
                    assert_never(__impossible)
        case WorkerTurnStart():
            match current.legacy_demand:
                case LegacyEmpty():
                    match current.durable_demand:
                        case DurableEmpty():
                            return current
                        case DurableNonEmpty():
                            return None
                        case __impossible:
                            assert_never(__impossible)
                case LegacyNonEmpty():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)
