# Generated by rocq-python-extraction (target: Python 3.14t)  # From payload_text.v:1:0
from itertools import islice  # From payload_text.v:1:0
from dataclasses import dataclass  # From payload_text.v:1:0
from fractions import Fraction  # From payload_text.v:1:0
from typing import (
    Any,
    Awaitable,
    Callable,
    Generic,
    Iterable,
    Iterator,
    Never,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)  # From payload_text.v:1:0

_CoForceT = TypeVar("_CoForceT")  # From payload_text.v:1:0
_ModuleArgT = TypeVar("_ModuleArgT")  # From payload_text.v:1:0
_ModuleRetT = TypeVar("_ModuleRetT")  # From payload_text.v:1:0
_StateTState = TypeVar("_StateTState")  # From payload_text.v:1:0
_StateTValue = TypeVar("_StateTValue")  # From payload_text.v:1:0
_StateTNext = TypeVar("_StateTNext")  # From payload_text.v:1:0
_IOValue = TypeVar("_IOValue")  # From payload_text.v:1:0
_IONext = TypeVar("_IONext")  # From payload_text.v:1:0


class _Impossible(RuntimeError):  # From payload_text.v:1:0
    pass  # From payload_text.v:1:0


def _impossible() -> Never:  # From payload_text.v:1:0
    raise _Impossible()  # From payload_text.v:1:0


class _RocqUtf8BoundaryError(UnicodeError):  # From payload_text.v:1:0
    pass  # From payload_text.v:1:0


class _RocqNumericDomainError(ValueError):  # From payload_text.v:1:0
    pass  # From payload_text.v:1:0


def _rocq_numeric_domain_error(
    kind: str, value: object
) -> Never:  # From payload_text.v:1:0
    raise _RocqNumericDomainError(
        f"Rocq {kind} value out of domain: {value!r}"
    )  # From payload_text.v:1:0


key = int  # finite-map module key alias  # From payload_text.v:1:0
elt = int  # finite-set module element alias  # From payload_text.v:1:0


def _rocq_positive_key(key: int) -> int:  # From payload_text.v:1:0
    if key <= 0:  # From payload_text.v:1:0
        raise _RocqNumericDomainError(
            f"positive map/set key", key
        )  # From payload_text.v:1:0
    return key  # From payload_text.v:1:0


def _rocq_string_key(key: str) -> str:  # From payload_text.v:1:0
    if not isinstance(key, str):  # From payload_text.v:1:0
        raise TypeError(
            f"Rocq string map/set key must be str: {key!r}"
        )  # From payload_text.v:1:0
    return key  # From payload_text.v:1:0


def _rocq_sorted_key(key: object) -> Any:  # From payload_text.v:1:0
    return (
        key.encode("utf-8") if isinstance(key, str) else key
    )  # From payload_text.v:1:0


def _rocq_map_add(
    key: object, value: object, mapping: dict[object, object]
) -> dict[object, object]:  # From payload_text.v:1:0
    result = dict(mapping)  # From payload_text.v:1:0
    result[key] = value  # From payload_text.v:1:0
    return result  # From payload_text.v:1:0


def _rocq_map_remove(
    key: object, mapping: dict[object, object]
) -> dict[object, object]:  # From payload_text.v:1:0
    result = dict(mapping)  # From payload_text.v:1:0
    result.pop(key, None)  # From payload_text.v:1:0
    return result  # From payload_text.v:1:0


def _rocq_map_elements(
    mapping: dict[object, object],
) -> list[tuple[object, object]]:  # From payload_text.v:1:0
    return sorted(
        mapping.items(), key=lambda item: _rocq_sorted_key(item[0])
    )  # From payload_text.v:1:0


def _rocq_map_fold(
    function: Callable[[object, object, object], object],
    mapping: dict[object, object],
    initial: object,
) -> object:  # From payload_text.v:1:0
    result = initial  # From payload_text.v:1:0
    for key, value in _rocq_map_elements(mapping):  # From payload_text.v:1:0
        result = function(key, value, result)  # From payload_text.v:1:0
    return result  # From payload_text.v:1:0


def _rocq_set_add(
    key: object, values: frozenset[object]
) -> frozenset[object]:  # From payload_text.v:1:0
    return frozenset((*values, key))  # From payload_text.v:1:0


def _rocq_set_remove(
    key: object, values: frozenset[object]
) -> frozenset[object]:  # From payload_text.v:1:0
    return frozenset(
        value for value in values if value != key
    )  # From payload_text.v:1:0


def _rocq_set_elements(
    values: frozenset[object],
) -> list[object]:  # From payload_text.v:1:0
    return sorted(values, key=_rocq_sorted_key)  # From payload_text.v:1:0


def _rocq_set_fold(
    function: Callable[[object, object], object],
    values: frozenset[object],
    initial: object,
) -> object:  # From payload_text.v:1:0
    result = initial  # From payload_text.v:1:0
    for value in _rocq_set_elements(values):  # From payload_text.v:1:0
        result = function(value, result)  # From payload_text.v:1:0
    return result  # From payload_text.v:1:0


def _rocq_string_cons(head: int, tail: str) -> str:  # From payload_text.v:1:0
    try:  # From payload_text.v:1:0
        return bytes([head]).decode("utf-8") + tail  # From payload_text.v:1:0
    except UnicodeDecodeError as exc:  # From payload_text.v:1:0
        raise _RocqUtf8BoundaryError(
            "Rocq string split crosses a UTF-8 boundary"
        ) from exc  # From payload_text.v:1:0


def _rocq_string_uncons(value: str) -> tuple[int, str]:  # From payload_text.v:1:0
    encoded = value.encode("utf-8")  # From payload_text.v:1:0
    if not encoded:  # From payload_text.v:1:0
        raise _Impossible()  # From payload_text.v:1:0
    try:  # From payload_text.v:1:0
        tail = encoded[1:].decode("utf-8")  # From payload_text.v:1:0
    except UnicodeDecodeError as exc:  # From payload_text.v:1:0
        raise _RocqUtf8BoundaryError(
            "Rocq string split crosses a UTF-8 boundary"
        ) from exc  # From payload_text.v:1:0
    return encoded[0], tail  # From payload_text.v:1:0


def _rocq_ascii_to_int(
    b0: bool, b1: bool, b2: bool, b3: bool, b4: bool, b5: bool, b6: bool, b7: bool
) -> int:  # From payload_text.v:1:0
    return sum(
        (1 << i) for i, bit in enumerate((b0, b1, b2, b3, b4, b5, b6, b7)) if bit
    )  # From payload_text.v:1:0


def _rocq_ascii_bits(
    value: int,
) -> tuple[bool, bool, bool, bool, bool, bool, bool, bool]:  # From payload_text.v:1:0
    if value < 0 or value > 255:  # From payload_text.v:1:0
        raise ValueError(
            "Rocq byte/ascii value out of range"
        )  # From payload_text.v:1:0
    return cast(
        tuple[bool, bool, bool, bool, bool, bool, bool, bool],
        tuple(bool(value & (1 << i)) for i in range(8)),
    )  # From payload_text.v:1:0


class StateT(Generic[_StateTState, _StateTValue]):  # From payload_text.v:1:0
    def __init__(
        self,
        step: Callable[[_StateTState], tuple[_StateTValue, _StateTState]],
        state: _StateTState | None = None,
    ) -> None:  # From payload_text.v:1:0
        self._step = step  # From payload_text.v:1:0
        self.state = state  # From payload_text.v:1:0

    def run(self, state: _StateTState) -> _StateTValue:  # From payload_text.v:1:0
        value, next_state = self._step(state)  # From payload_text.v:1:0
        self.state = next_state  # From payload_text.v:1:0
        return value  # From payload_text.v:1:0

    def run_with_state(
        self, state: _StateTState
    ) -> tuple[_StateTValue, _StateTState]:  # From payload_text.v:1:0
        result = self._step(state)  # From payload_text.v:1:0
        self.state = result[1]  # From payload_text.v:1:0
        return result  # From payload_text.v:1:0

    def bind(
        self, f: Callable[[_StateTValue], StateT[_StateTState, _StateTNext]]
    ) -> StateT[_StateTState, _StateTNext]:  # From payload_text.v:1:0
        def run_bound(
            state: _StateTState,
        ) -> tuple[_StateTNext, _StateTState]:  # From payload_text.v:1:0
            value, next_state = self._step(state)  # From payload_text.v:1:0
            return f(value).run_with_state(next_state)  # From payload_text.v:1:0

        return StateT(run_bound, self.state)  # From payload_text.v:1:0

    @classmethod  # From payload_text.v:1:0
    def pure(
        cls, value: _StateTValue
    ) -> StateT[_StateTState, _StateTValue]:  # From payload_text.v:1:0
        return StateT(lambda state: (value, state))  # From payload_text.v:1:0

    @classmethod  # From payload_text.v:1:0
    def get_state(cls) -> StateT[_StateTState, _StateTState]:  # From payload_text.v:1:0
        return StateT(lambda state: (state, state))  # From payload_text.v:1:0

    @classmethod  # From payload_text.v:1:0
    def put_state(
        cls, new_state: _StateTState
    ) -> StateT[_StateTState, None]:  # From payload_text.v:1:0
        return StateT(lambda _state: (None, new_state))  # From payload_text.v:1:0


class IO(Generic[_IOValue]):  # From payload_text.v:1:0
    def __init__(
        self, thunk: Callable[[], Awaitable[_IOValue]]
    ) -> None:  # From payload_text.v:1:0
        self._thunk = thunk  # From payload_text.v:1:0

    async def run(self) -> _IOValue:  # From payload_text.v:1:0
        return await self._thunk()  # From payload_text.v:1:0

    def bind(
        self, f: Callable[[_IOValue], IO[_IONext]]
    ) -> IO[_IONext]:  # From payload_text.v:1:0
        async def run_bound() -> _IONext:  # From payload_text.v:1:0
            value = await self.run()  # From payload_text.v:1:0
            return await f(value).run()  # From payload_text.v:1:0

        return IO(run_bound)  # From payload_text.v:1:0

    @classmethod  # From payload_text.v:1:0
    def pure(cls, value: _IOValue) -> IO[_IOValue]:  # From payload_text.v:1:0
        async def run_pure() -> _IOValue:  # From payload_text.v:1:0
            return value  # From payload_text.v:1:0

        return IO(run_pure)  # From payload_text.v:1:0


def coforce(value: Callable[[], _CoForceT]) -> _CoForceT:  # From payload_text.v:1:0
    return value()  # From payload_text.v:1:0


def coprefix_eq(
    n: int, left: Iterable[object], right: Iterable[object]
) -> bool:  # From payload_text.v:1:0
    return tuple(islice(iter(left), n)) == tuple(
        islice(iter(right), n)
    )  # From payload_text.v:1:0


def coprefix_hash(n: int, value: Iterable[object]) -> int:  # From payload_text.v:1:0
    return hash(tuple(islice(iter(value), n)))  # From payload_text.v:1:0


class __ModuleNamespace:  # From payload_text.v:1:0
    pass  # From payload_text.v:1:0


def __apply_applicative(
    cache: dict[int, _ModuleRetT],
    build: Callable[[_ModuleArgT], _ModuleRetT],
    arg: _ModuleArgT,
) -> _ModuleRetT:  # From payload_text.v:1:0
    key = id(arg)  # From payload_text.v:1:0
    cached = cache.get(key)  # From payload_text.v:1:0
    if cached is None:  # From payload_text.v:1:0
        cached = build(arg)  # From payload_text.v:1:0
        cache[key] = cached  # From payload_text.v:1:0
    return cached  # From payload_text.v:1:0


__ = None  # erased logical argument  # From payload_text.v:1:0
# bool: remapped to Python primitive  # From payload_text.v:1:0

# byte: remapped to Python primitive  # From payload_text.v:1:0

# ascii: remapped to Python primitive  # From payload_text.v:1:0

# string: remapped to Python primitive  # From payload_text.v:1:0

event_name: str = _rocq_string_cons(
    _rocq_ascii_to_int(False, False, False, False, True, True, True, False),
    _rocq_string_cons(
        _rocq_ascii_to_int(True, False, True, False, True, True, True, False),
        _rocq_string_cons(
            _rocq_ascii_to_int(False, False, True, True, False, True, True, False),
            _rocq_string_cons(
                _rocq_ascii_to_int(False, False, True, True, False, True, True, False),
                _rocq_string_cons(
                    _rocq_ascii_to_int(
                        True, True, True, True, True, False, True, False
                    ),
                    _rocq_string_cons(
                        _rocq_ascii_to_int(
                            False, True, False, False, True, True, True, False
                        ),
                        _rocq_string_cons(
                            _rocq_ascii_to_int(
                                True, False, True, False, False, True, True, False
                            ),
                            _rocq_string_cons(
                                _rocq_ascii_to_int(
                                    True, False, False, False, True, True, True, False
                                ),
                                _rocq_string_cons(
                                    _rocq_ascii_to_int(
                                        True,
                                        False,
                                        True,
                                        False,
                                        True,
                                        True,
                                        True,
                                        False,
                                    ),
                                    _rocq_string_cons(
                                        _rocq_ascii_to_int(
                                            True,
                                            False,
                                            True,
                                            False,
                                            False,
                                            True,
                                            True,
                                            False,
                                        ),
                                        _rocq_string_cons(
                                            _rocq_ascii_to_int(
                                                True,
                                                True,
                                                False,
                                                False,
                                                True,
                                                True,
                                                True,
                                                False,
                                            ),
                                            _rocq_string_cons(
                                                _rocq_ascii_to_int(
                                                    False,
                                                    False,
                                                    True,
                                                    False,
                                                    True,
                                                    True,
                                                    True,
                                                    False,
                                                ),
                                                "",
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
)  # From payload_text.v:1:0
event_name_bytes: bytes = b"pull_request"  # From payload_text.v:1:0
newline_byte: int = 10  # From payload_text.v:1:0


def first_char_or_newline(s: str) -> int:  # From payload_text.v:1:0
    return (
        lambda __s: (
            (
                lambda: _rocq_ascii_to_int(
                    False, True, False, True, False, False, False, False
                )
            )()
            if __s == ""
            else (lambda __pair: (lambda c, s0: c)(__pair[0], __pair[1]))(
                _rocq_string_uncons(__s)
            )
        )
    )(s)  # From payload_text.v:1:0
