# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass, replace
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
    final,
)


class TaskKind:
    pass


@final
@dataclass(frozen=True)
class TaskCI(TaskKind):
    pass


@final
@dataclass(frozen=True)
class TaskThread(TaskKind):
    pass


@final
@dataclass(frozen=True)
class TaskSpec(TaskKind):
    pass


@final
@dataclass(frozen=True)
class TaskAsk(TaskKind):
    pass


@final
@dataclass(frozen=True)
class TaskDefer(TaskKind):
    pass


TaskKindT = TaskCI | TaskThread | TaskSpec | TaskAsk | TaskDefer


class TaskStatus:
    pass


@final
@dataclass(frozen=True)
class StatusPending(TaskStatus):
    pass


@final
@dataclass(frozen=True)
class StatusCompleted(TaskStatus):
    pass


@final
@dataclass(frozen=True)
class StatusBlocked(TaskStatus):
    pass


TaskStatusT = StatusPending | StatusCompleted | StatusBlocked


@final
@dataclass(frozen=True)
class TaskRow:
    title: str
    description: str
    kind: TaskKind
    status: TaskStatus
    source_comment: int | None
    lineage_comments: list[int]


# ExecutionLease: singleton inductive, constructor was Build_ExecutionLease


def lease_task(e: ExecutionLease) -> int:
    lease_task0 = e
    return lease_task0


@final
@dataclass(frozen=True)
class SplitChild:
    child_task: int
    child_title: str
    child_description: str


class RescopeOp:
    pass


@final
@dataclass(frozen=True)
class KeepTask(RescopeOp):
    task: int


@final
@dataclass(frozen=True)
class RewriteTask(RescopeOp):
    task: int
    new_title: str
    new_description: str


@final
@dataclass(frozen=True)
class RewriteAnchor(RescopeOp):
    task: int
    new_anchor: int | None


@final
@dataclass(frozen=True)
class MergeTasks(RescopeOp):
    task: int
    sources: list[int]
    new_title: str
    new_description: str


@final
@dataclass(frozen=True)
class SplitTask(RescopeOp):
    task: int
    children: list[SplitChild]


@final
@dataclass(frozen=True)
class CompleteTask(RescopeOp):
    task: int


RescopeOpT = (
    KeepTask | RewriteTask | RewriteAnchor | MergeTasks | SplitTask | CompleteTask
)


class RescopeReleaseKind:
    pass


@final
@dataclass(frozen=True)
class ReleaseACT(RescopeReleaseKind):
    pass


@final
@dataclass(frozen=True)
class ReleaseDO(RescopeReleaseKind):
    pass


RescopeReleaseKindT = ReleaseACT | ReleaseDO


@final
@dataclass(frozen=True)
class RescopeRelease:
    release_kind: RescopeReleaseKind
    release_decision: RescopeOp

    def task_id(self) -> int:
        release = self
        return rescope_task_id(release.release_decision)


def task_executable(kind0: TaskKind) -> bool:
    match kind0:
        case TaskCI():
            return True
        case TaskThread():
            return True
        case TaskSpec():
            return True
        case TaskAsk():
            return False
        case TaskDefer():
            return False
        case __impossible:
            assert_never(__impossible)


def task_row_executable(row: TaskRow) -> bool:
    match row.status:
        case StatusPending():
            return task_executable(row.kind)
        case StatusCompleted():
            return False
        case StatusBlocked():
            return False
        case __impossible:
            assert_never(__impossible)


def task_preempt_rank(kind0: TaskKind) -> int | None:
    match kind0:
        case TaskCI():
            return 0
        case TaskThread():
            return 1
        case TaskSpec():
            return 2
        case TaskAsk():
            return None
        case TaskDefer():
            return None
        case __impossible:
            assert_never(__impossible)


def task_requires_abort(
    new_row: TaskRow,
    current_row: TaskRow,
) -> bool:
    __option = task_preempt_rank(new_row.kind)
    if __option is None:
        return False
    new_rank = __option
    __option = task_preempt_rank(current_row.kind)
    if __option is None:
        return False
    current_rank = __option
    return new_rank < current_rank


def find_comment_duplicate(
    comment: int,
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    for task in order:
        __option = rows.get(_rocq_positive_key(task))
        if __option is None:
            continue
        row = __option
        __option = row.source_comment
        if __option is None:
            continue
        existing = __option
        if existing == comment:
            return task
        continue
    return None


def row_has_pending_title(
    candidate_title: str,
    row: TaskRow,
) -> bool:
    match row.status:
        case StatusPending():
            return row.title == candidate_title
        case StatusCompleted():
            return False
        case StatusBlocked():
            return False
        case __impossible:
            assert_never(__impossible)


def task_has_pending_title(
    candidate_title: str,
    task: int,
    rows: dict[int, TaskRow],
) -> bool:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return False
    row = __option
    return row_has_pending_title(candidate_title, row)


def find_pending_title_duplicate(
    candidate_title: str,
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    for task in order:
        if task_has_pending_title(candidate_title, task, rows):
            return task
        continue
    return None


def enqueue_task(
    task: int,
    row: TaskRow,
    order: list[int],
    rows: dict[int, TaskRow],
) -> tuple[tuple[list[int], dict[int, TaskRow]], int]:
    __option = row.source_comment
    if __option is None:
        __option = find_pending_title_duplicate(row.title, order, rows)
        if __option is None:
            return (
                (
                    order + [task],
                    _rocq_map_add(
                        _rocq_positive_key(task),
                        row,
                        rows,
                    ),
                ),
                task,
            )
        existing = __option
        return (
            (
                order,
                rows,
            ),
            existing,
        )
    comment = __option
    __option = find_comment_duplicate(comment, order, rows)
    if __option is None:
        return (
            (
                order + [task],
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row,
                    rows,
                ),
            ),
            task,
        )
    existing = __option
    return (
        (
            order,
            rows,
        ),
        existing,
    )


def pick_first_ci(
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    for task in order:
        __option = rows.get(_rocq_positive_key(task))
        if __option is None:
            continue
        row = __option
        if task_row_executable(row) and isinstance(row.kind, TaskCI):
            return task
        continue
    return None


def pick_first_non_ci(
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    for task in order:
        __option = rows.get(_rocq_positive_key(task))
        if __option is None:
            continue
        row = __option
        if task_row_executable(row) and not isinstance(row.kind, TaskCI):
            return task
        continue
    return None


def pick_next_task(
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __option = pick_first_ci(order, rows)
    if __option is None:
        return pick_first_non_ci(order, rows)
    task = __option
    return task


def begin_task(
    task: int,
    lease: ExecutionLease | None,
    rows: dict[int, TaskRow],
) -> ExecutionLease | None:
    __option = lease
    if __option is None:
        __option = rows.get(_rocq_positive_key(task))
        if __option is None:
            return None
        row = __option
        if task_row_executable(row):
            return task
        return None
    e = __option
    return None


def clear_matching_lease(
    task: int,
    lease: ExecutionLease | None,
) -> ExecutionLease | None:
    __option = lease
    if __option is None:
        return None
    active = __option
    if lease_task(active) == task:
        return None
    return lease


def complete_task(
    task: int,
    lease: ExecutionLease | None,
    rows: dict[int, TaskRow],
) -> tuple[ExecutionLease | None, dict[int, TaskRow]]:
    lease_ = clear_matching_lease(task, lease)
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return (
            lease_,
            rows,
        )
    row = __option
    row_ = replace(
        row,
        status=StatusCompleted(),
    )
    return (
        lease_,
        _rocq_map_add(
            _rocq_positive_key(task),
            row_,
            rows,
        ),
    )


def abort_task(
    task: int,
    lease: ExecutionLease | None,
) -> ExecutionLease | None:
    __option = lease
    if __option is None:
        return None
    active = __option
    if lease_task(active) == task:
        return None
    return lease


def task_visible_after_rescope(row: TaskRow) -> bool:
    return not isinstance(row.status, StatusCompleted)


def unblock_task_row(
    task: int,
    row: TaskRow,
    rows: dict[int, TaskRow],
) -> dict[int, TaskRow]:
    match row.status:
        case StatusPending():
            return rows
        case StatusCompleted():
            return rows
        case StatusBlocked():
            row_ = replace(
                row,
                status=StatusPending(),
            )
            return _rocq_map_add(
                _rocq_positive_key(task),
                row_,
                rows,
            )
        case __impossible:
            assert_never(__impossible)


def unblock_task_if_present(
    task: int,
    rows: dict[int, TaskRow],
) -> dict[int, TaskRow]:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return rows
    row = __option
    return unblock_task_row(
        task,
        row,
        rows,
    )


def unblock_task_rows(
    order: list[int],
    rows: dict[int, TaskRow],
) -> dict[int, TaskRow]:
    for task in order:
        rows = unblock_task_if_present(task, rows)
        continue
    return rows


def unblock_tasks(
    order: list[int],
    rows: dict[int, TaskRow],
) -> dict[int, TaskRow]:
    return unblock_task_rows(order, rows)


def rescope_task_id(op: RescopeOp) -> int:
    match op:
        case KeepTask(task):
            return task
        case RewriteTask(task, new_title, new_description):
            return task
        case RewriteAnchor(task, new_anchor):
            return task
        case MergeTasks(task, sources, new_title, new_description):
            return task
        case SplitTask(task, children):
            return task
        case CompleteTask(task):
            return task
        case __impossible:
            assert_never(__impossible)


def op_covers_task(
    task: int,
    ops: list[RescopeOp],
) -> bool:
    for op in ops:
        if rescope_task_id(op) == task:
            return True
        continue
    return False


def rescope_ops_cover_snapshot(
    snapshot_order: list[int],
    ops: list[RescopeOp],
) -> bool:
    for task in snapshot_order:
        if op_covers_task(task, ops):
            continue
        return False
    return True


def release_for_task(
    task: int,
    releases: list[RescopeRelease],
) -> RescopeOp | None:
    for release in releases:
        if release.task_id() == task:
            return release.release_decision
        continue
    return None


def normalize_rescope_batch(
    snapshot_order: list[int],
    releases: list[RescopeRelease],
) -> list[RescopeOp]:
    __list = snapshot_order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = normalize_rescope_batch(rest, releases)
    __option = release_for_task(task, releases)
    if __option is None:
        return rest_
    op = __option
    return [op] + rest_


def append_unique(
    cid: int,
    acc: list[int],
) -> list[int]:
    if cid in acc:
        return acc
    return acc + [cid]


def append_unique_list(
    cids: list[int],
    acc: list[int],
) -> list[int]:
    for cid in cids:
        acc = append_unique(cid, acc)
        continue
    return acc


def append_unique_option(
    cid: int | None,
    acc: list[int],
) -> list[int]:
    __option = cid
    if __option is None:
        return acc
    c = __option
    return append_unique(c, acc)


def fold_source_lineage_into(
    rows: dict[int, TaskRow],
    src: int,
    acc: list[int],
) -> list[int]:
    __option = rows.get(_rocq_positive_key(src))
    if __option is None:
        return acc
    row = __option
    with_lineage = append_unique_list(row.lineage_comments, acc)
    return append_unique_option(row.source_comment, with_lineage)


def collect_source_lineages(
    sources: list[int],
    rows: dict[int, TaskRow],
    acc: list[int],
) -> list[int]:
    for src in sources:
        acc = fold_source_lineage_into(
            rows,
            src,
            acc,
        )
        continue
    return acc


def split_child_row(
    source_row: TaskRow,
    spec: SplitChild,
) -> TaskRow:
    return replace(
        source_row,
        title=spec.child_title,
        description=spec.child_description,
        status=StatusPending(),
    )


def add_split_kids(
    children: list[SplitChild],
    source_row: TaskRow,
    rows: dict[int, TaskRow],
    pending_ids: list[int],
) -> tuple[dict[int, TaskRow], list[int]]:
    for spec in children:
        child_row = split_child_row(source_row, spec)
        rows_ = _rocq_map_add(
            _rocq_positive_key(spec.child_task),
            child_row,
            rows,
        )
        pending_ = pending_ids + [spec.child_task]
        rows, pending_ids = rows_, pending_
        continue
    return (
        rows,
        pending_ids,
    )


def apply_rescope_op(
    op: RescopeOp,
    task: int,
    row: TaskRow,
    rows: dict[int, TaskRow],
    pending_ids: list[int],
    completed_ids: list[int],
) -> tuple[tuple[dict[int, TaskRow], list[int]], list[int]]:
    if task_visible_after_rescope(row):
        match op:
            case KeepTask(task0):
                return (
                    (
                        rows,
                        pending_ids + [task],
                    ),
                    completed_ids,
                )
            case RewriteTask(task0, new_title, new_description):
                row_ = replace(
                    row,
                    title=new_title,
                    description=new_description,
                )
                return (
                    (
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids + [task],
                    ),
                    completed_ids,
                )
            case RewriteAnchor(task0, new_anchor):
                extended = append_unique_option(new_anchor, row.lineage_comments)
                row_ = replace(
                    row,
                    source_comment=new_anchor,
                    lineage_comments=extended,
                )
                return (
                    (
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids + [task],
                    ),
                    completed_ids,
                )
            case MergeTasks(task0, sources, new_title, new_description):
                merged = collect_source_lineages(
                    sources,
                    rows,
                    row.lineage_comments,
                )
                row_ = replace(
                    row,
                    title=new_title,
                    description=new_description,
                    lineage_comments=merged,
                )
                return (
                    (
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids + [task],
                    ),
                    completed_ids,
                )
            case SplitTask(task0, children):
                closed = replace(
                    row,
                    status=StatusCompleted(),
                )
                rows_with_source = _rocq_map_add(
                    _rocq_positive_key(task),
                    closed,
                    rows,
                )
                __pair = add_split_kids(children, row, rows_with_source, pending_ids)
                rows_ = __pair[0]
                pending_ = __pair[1]
                return (
                    (
                        rows_,
                        pending_,
                    ),
                    completed_ids + [task],
                )
            case CompleteTask(task0):
                row_ = replace(
                    row,
                    status=StatusCompleted(),
                )
                return (
                    (
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids,
                    ),
                    completed_ids + [task],
                )
            case __impossible:
                assert_never(__impossible)
    return (
        (
            rows,
            pending_ids,
        ),
        completed_ids,
    )


def apply_rescope_ops(
    ops: list[RescopeOp],
    rows: dict[int, TaskRow],
    pending_ids: list[int],
    completed_ids: list[int],
) -> tuple[tuple[dict[int, TaskRow], list[int]], list[int]]:
    for op in ops:
        task = rescope_task_id(op)
        __option = rows.get(_rocq_positive_key(task))
        if __option is None:
            continue
        row = __option
        __pair = apply_rescope_op(op, task, row, rows, pending_ids, completed_ids)
        p = __pair[0]
        completed_ids_ = __pair[1]
        __pair = p
        rows_ = __pair[0]
        pending_ids_ = __pair[1]
        rows, pending_ids, completed_ids = rows_, pending_ids_, completed_ids_
        continue
    return (
        (
            rows,
            pending_ids,
        ),
        completed_ids,
    )


def completed_tasks_in_order(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    while True:
        __list = order
        if __list == []:
            return []
        task = __list[0]
        rest = __list[1:]
        __option = rows.get(_rocq_positive_key(task))
        if __option is None:
            order, rows = rest, rows
            continue
        row = __option
        match row.status:
            case StatusPending():
                order, rows = rest, rows
                continue
            case StatusCompleted():
                return [task] + completed_tasks_in_order(rest, rows)
            case StatusBlocked():
                order, rows = rest, rows
                continue
            case __impossible:
                assert_never(__impossible)


def preserve_newly_added(
    snapshot_order: list[int],
    current_order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = current_order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = preserve_newly_added(
        snapshot_order,
        rest,
        rows,
    )
    if task in snapshot_order:
        return rest_
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return rest_
    row = __option
    match row.status:
        case StatusPending():
            return [task] + rest_
        case StatusCompleted():
            return rest_
        case StatusBlocked():
            return [task] + rest_
        case __impossible:
            assert_never(__impossible)


def task_matches_ci_filter(
    include_ci: bool,
    rows: dict[int, TaskRow],
    task: int,
) -> bool:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return False
    row = __option
    if include_ci:
        return isinstance(row.kind, TaskCI)
    return not isinstance(row.kind, TaskCI)


def collect_tasks(
    include_ci: bool,
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = collect_tasks(
        include_ci,
        rest,
        rows,
    )
    if task_matches_ci_filter(include_ci, rows, task):
        return [task] + rest_
    return rest_


def stable_ci_first(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    ci = collect_tasks(
        True,
        order,
        rows,
    )
    non_ci = collect_tasks(
        False,
        order,
        rows,
    )
    return ci + non_ci


def task_title_changed(
    before_row: TaskRow,
    after_row: TaskRow,
) -> bool:
    return before_row.title != after_row.title


def task_description_changed(
    before_row: TaskRow,
    after_row: TaskRow,
) -> bool:
    return before_row.description != after_row.description


def task_metadata_changed(
    before_row: TaskRow,
    after_row: TaskRow,
) -> bool:
    if task_title_changed(before_row, after_row):
        return True
    return task_description_changed(before_row, after_row)


def apply_rescope(
    snapshot_order: list[int],
    current_order: list[int],
    rows: dict[int, TaskRow],
    ops: list[RescopeOp],
) -> tuple[list[int], dict[int, TaskRow]]:
    __pair = apply_rescope_ops(ops, rows, [], [])
    p = __pair[0]
    newly_completed = __pair[1]
    __pair = p
    rows_ = __pair[0]
    pending_ids = __pair[1]
    completed_existing = completed_tasks_in_order(current_order, rows)
    newly_added = preserve_newly_added(
        snapshot_order,
        current_order,
        rows_,
    )
    pending_order = stable_ci_first(pending_ids, rows_)
    return (
        pending_order + completed_existing + newly_completed + newly_added,
        rows_,
    )


def apply_batched_rescope(
    snapshot_order: list[int],
    current_order: list[int],
    rows: dict[int, TaskRow],
    releases: list[RescopeRelease],
) -> tuple[list[int], dict[int, TaskRow]]:
    ops = normalize_rescope_batch(snapshot_order, releases)
    return apply_rescope(
        snapshot_order,
        current_order,
        rows,
        ops,
    )


def list_subset(
    xs: list[int],
    ys: list[int],
) -> bool:
    __list = xs
    if __list == []:
        return True
    x = __list[0]
    rest = __list[1:]
    return x in ys and list_subset(rest, ys)


def source_anchor_in_lineage(
    anchor: int | None,
    lineage: list[int],
) -> bool:
    __option = anchor
    if __option is None:
        return True
    c = __option
    return c in lineage


def merge_target_lineage_includes_source(
    target_row: TaskRow,
    src_row: TaskRow,
) -> bool:
    target_lineage = target_row.lineage_comments
    src_lineage_ok = list_subset(src_row.lineage_comments, target_lineage)
    src_anchor_ok = source_anchor_in_lineage(src_row.source_comment, target_lineage)
    return src_lineage_ok and src_anchor_ok


def merge_preserves_source_lineage(
    sources: list[int],
    rows_before: dict[int, TaskRow],
    target_row_after: TaskRow,
) -> bool:
    for src in sources:
        __option = rows_before.get(_rocq_positive_key(src))
        if __option is None:
            continue
        src_row = __option
        if merge_target_lineage_includes_source(target_row_after, src_row):
            continue
        return False
    return True


def optional_anchors_match(
    a: int | None,
    b: int | None,
) -> bool:
    __option = a
    if __option is None:
        __option = b
        if __option is None:
            return True
        p = __option
        return False
    x = __option
    __option = b
    if __option is None:
        return False
    y = __option
    return x == y


def split_child_inherits_source(
    source_row: TaskRow,
    child_row: TaskRow,
) -> bool:
    src_lineage = source_row.lineage_comments
    child_lineage = child_row.lineage_comments
    lineage_ok = list_subset(src_lineage, child_lineage)
    src_anchor = source_row.source_comment
    child_anchor = child_row.source_comment
    anchor_ok = optional_anchors_match(src_anchor, child_anchor)
    return lineage_ok and anchor_ok


def split_preserves_source_lineage(
    children: list[int],
    source_row: TaskRow,
    rows_after: dict[int, TaskRow],
) -> bool:
    for child in children:
        __option = rows_after.get(_rocq_positive_key(child))
        if __option is None:
            return False
        child_row = __option
        if split_child_inherits_source(source_row, child_row):
            continue
        return False
    return True


def rescope_affects_active_task(
    lease: ExecutionLease | None,
    rows_before: dict[int, TaskRow],
    rows_after: dict[int, TaskRow],
) -> bool:
    __option = lease
    if __option is None:
        return False
    active = __option
    __option = rows_before.get(_rocq_positive_key(lease_task(active)))
    if __option is None:
        return False
    before_row = __option
    __option = rows_after.get(_rocq_positive_key(lease_task(active)))
    if __option is None:
        return True
    after_row = __option
    match after_row.status:
        case StatusPending():
            return task_metadata_changed(before_row, after_row)
        case StatusCompleted():
            return True
        case StatusBlocked():
            return task_metadata_changed(before_row, after_row)
        case __impossible:
            assert_never(__impossible)


def should_abort_for_new_task(
    new_task: int,
    lease: ExecutionLease | None,
    rows: dict[int, TaskRow],
) -> bool:
    __option = lease
    if __option is None:
        return False
    active = __option
    if new_task == lease_task(active):
        return False
    __option = rows.get(_rocq_positive_key(new_task))
    if __option is None:
        return False
    new_row = __option
    __option = rows.get(_rocq_positive_key(lease_task(active)))
    if __option is None:
        return False
    current_row = __option
    return task_requires_abort(new_row, current_row)


def complete_task_visible(
    task: int,
    rows: dict[int, TaskRow],
) -> tuple[dict[int, TaskRow], int | None]:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return (
            rows,
            None,
        )
    row = __option
    match row.status:
        case StatusPending():
            row_ = replace(
                row,
                status=StatusCompleted(),
            )
            return (
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row_,
                    rows,
                ),
                row.source_comment,
            )
        case StatusCompleted():
            return (
                rows,
                None,
            )
        case StatusBlocked():
            row_ = replace(
                row,
                status=StatusCompleted(),
            )
            return (
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row_,
                    rows,
                ),
                row.source_comment,
            )
        case __impossible:
            assert_never(__impossible)


class TaskChange:
    pass


@final
@dataclass(frozen=True)
class TaskCompleted(TaskChange):
    task: int


@final
@dataclass(frozen=True)
class TaskCancelled(TaskChange):
    task: int


@final
@dataclass(frozen=True)
class TaskModified(TaskChange):
    task: int
    new_title: str
    new_description: str


TaskChangeT = TaskCompleted | TaskCancelled | TaskModified


def task_change(
    task: int,
    rows_before: dict[int, TaskRow],
    rows_after: dict[int, TaskRow],
) -> TaskChange | None:
    __option = rows_before.get(_rocq_positive_key(task))
    if __option is None:
        return None
    before_row = __option
    __option = before_row.source_comment
    if __option is None:
        return None
    p = __option
    match before_row.status:
        case StatusPending():
            __option = rows_after.get(_rocq_positive_key(task))
            if __option is None:
                return TaskCancelled(task)
            after_row = __option
            match after_row.status:
                case StatusPending():
                    if task_metadata_changed(before_row, after_row):
                        return TaskModified(
                            task,
                            after_row.title,
                            after_row.description,
                        )
                    return None
                case StatusCompleted():
                    return TaskCompleted(task)
                case StatusBlocked():
                    if task_metadata_changed(before_row, after_row):
                        return TaskModified(
                            task,
                            after_row.title,
                            after_row.description,
                        )
                    return None
                case __impossible:
                    assert_never(__impossible)
        case StatusCompleted():
            return None
        case StatusBlocked():
            __option = rows_after.get(_rocq_positive_key(task))
            if __option is None:
                return TaskCancelled(task)
            after_row = __option
            match after_row.status:
                case StatusPending():
                    if task_metadata_changed(before_row, after_row):
                        return TaskModified(
                            task,
                            after_row.title,
                            after_row.description,
                        )
                    return None
                case StatusCompleted():
                    return TaskCompleted(task)
                case StatusBlocked():
                    if task_metadata_changed(before_row, after_row):
                        return TaskModified(
                            task,
                            after_row.title,
                            after_row.description,
                        )
                    return None
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)


def compute_task_changes(
    snapshot_order: list[int],
    rows_before: dict[int, TaskRow],
    rows_after: dict[int, TaskRow],
) -> list[TaskChange]:
    __list = snapshot_order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = compute_task_changes(
        rest,
        rows_before,
        rows_after,
    )
    __option = task_change(task, rows_before, rows_after)
    if __option is None:
        return rest_
    change = __option
    return [change] + rest_


def task_changes_materially_significant(changes: list[TaskChange]) -> bool:
    __list = changes
    if __list == []:
        return False
    t0 = __list[0]
    l = __list[1:]
    return True


def batched_rescope_materially_significant(
    snapshot_order: list[int],
    current_order: list[int],
    rows: dict[int, TaskRow],
    releases: list[RescopeRelease],
) -> bool:
    __pair = apply_batched_rescope(snapshot_order, current_order, rows, releases)
    l = __pair[0]
    rows_after = __pair[1]
    changes = compute_task_changes(
        snapshot_order,
        rows,
        rows_after,
    )
    return task_changes_materially_significant(changes)


def remove_from_order(
    task: int,
    order: list[int],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    t0 = __list[0]
    rest = __list[1:]
    rest_ = remove_from_order(task, rest)
    if t0 == task:
        return rest_
    return [t0] + rest_


def cleanup_aborted_task(
    task: int,
    lease: ExecutionLease | None,
    order: list[int],
    rows: dict[int, TaskRow],
) -> tuple[tuple[ExecutionLease | None, list[int]], dict[int, TaskRow]]:
    lease_ = clear_matching_lease(task, lease)
    order_ = remove_from_order(task, order)
    rows_ = _rocq_map_remove(
        _rocq_positive_key(task),
        rows,
    )
    return (
        (
            lease_,
            order_,
        ),
        rows_,
    )


def task_still_pending(
    task: int,
    rows: dict[int, TaskRow],
) -> bool:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return False
    row = __option
    return isinstance(row.status, StatusPending)


class IntentOutcome:
    pass


@final
@dataclass(frozen=True)
class OutcomeHonored(IntentOutcome):
    pass


@final
@dataclass(frozen=True)
class OutcomeReshaped(IntentOutcome):
    pass


@final
@dataclass(frozen=True)
class OutcomeSuperseded(IntentOutcome):
    pass


@final
@dataclass(frozen=True)
class OutcomeNoOp(IntentOutcome):
    pass


IntentOutcomeT = OutcomeHonored | OutcomeReshaped | OutcomeSuperseded | OutcomeNoOp


@final
@dataclass(frozen=True)
class IntentRow:
    intent_comment_id: int
    intent_author: int
    intent_index: int


@final
@dataclass(frozen=True)
class VerdictRow:
    verdict_intent_id: int
    verdict_outcome: IntentOutcome
    verdict_by_intent: int | None
    verdict_affected_tasks: list[int]

    def is_superseded(self) -> bool:
        verdict = self
        return isinstance(verdict.verdict_outcome, OutcomeSuperseded)


@final
@dataclass(frozen=True)
class TaskWithIntents:
    twi_id: int
    twi_row: TaskRow
    twi_contributing: list[int]


class DispositionKind:
    pass


@final
@dataclass(frozen=True)
class DispMaterial(DispositionKind):
    pass


@final
@dataclass(frozen=True)
class DispAggregation(DispositionKind):
    pass


@final
@dataclass(frozen=True)
class DispUnhandled(DispositionKind):
    pass


DispositionKindT = DispMaterial | DispAggregation | DispUnhandled


@final
@dataclass(frozen=True)
class IntentDisposition:
    disp_kind: DispositionKind
    disp_affected: list[int]


class NotifyDecision:
    pass


@final
@dataclass(frozen=True)
class NotifySilent(NotifyDecision):
    pass


@final
@dataclass(frozen=True)
class NotifyMaterial(NotifyDecision):
    pass


@final
@dataclass(frozen=True)
class NotifyUnhandled(NotifyDecision):
    pass


@final
@dataclass(frozen=True)
class NotifyOverridden(NotifyDecision):
    pass


NotifyDecisionT = NotifySilent | NotifyMaterial | NotifyUnhandled | NotifyOverridden


def optional_anchor_changed(
    a: int | None,
    b: int | None,
) -> bool:
    return a != b


def status_flipped_to_completed(
    orig: TaskRow,
    result: TaskRow,
) -> bool:
    if isinstance(result.status, StatusCompleted):
        return not isinstance(orig.status, StatusCompleted)
    return False


def row_material_changed(
    orig: TaskRow,
    result: TaskRow,
) -> bool:
    if status_flipped_to_completed(orig, result):
        return True
    if orig.title != result.title:
        return True
    if orig.description != result.description:
        return True
    return optional_anchor_changed(orig.source_comment, result.source_comment)


def task_material_changed(
    orig: TaskRow | None,
    result: TaskRow,
) -> bool:
    __option = orig
    if __option is None:
        return True
    o = __option
    return row_material_changed(o, result)


def intent_attributed_tasks_in(
    intent: int,
    tasks: list[TaskWithIntents],
) -> list[TaskWithIntents]:
    while True:
        __list = tasks
        if __list == []:
            return []
        t0 = __list[0]
        rest = __list[1:]
        if intent in t0.twi_contributing:
            return [t0] + intent_attributed_tasks_in(intent, rest)
        intent, tasks = intent, rest
        continue


def any_attributed_material(
    orig_rows: dict[int, TaskRow],
    attributed: list[TaskWithIntents],
) -> bool:
    for t0 in attributed:
        orig = orig_rows.get(_rocq_positive_key(t0.twi_id))
        if task_material_changed(orig, t0.twi_row):
            return True
        continue
    return False


def task_ids_of(ts: list[TaskWithIntents]) -> list[int]:
    __list = ts
    if __list == []:
        return []
    t0 = __list[0]
    rest = __list[1:]
    return [t0.twi_id] + task_ids_of(rest)


def classify_intent(
    intent: int,
    result_tasks: list[TaskWithIntents],
    orig_rows: dict[int, TaskRow],
) -> IntentDisposition:
    attributed = intent_attributed_tasks_in(intent, result_tasks)
    __list = attributed
    if __list == []:
        return IntentDisposition(
            disp_kind=DispUnhandled(),
            disp_affected=[],
        )
    t0 = __list[0]
    l = __list[1:]
    if any_attributed_material(orig_rows, attributed):
        return IntentDisposition(
            disp_kind=DispMaterial(),
            disp_affected=task_ids_of(attributed),
        )
    return IntentDisposition(
        disp_kind=DispAggregation(),
        disp_affected=task_ids_of(attributed),
    )


def find_disposition(
    intent: int,
    entries: list[tuple[int, IntentDisposition]],
) -> IntentDisposition | None:
    for p in entries:
        __pair = p
        cid = __pair[0]
        disp = __pair[1]
        if cid == intent:
            return disp
        continue
    return None


def classify_rescope_intents(
    intents: list[IntentRow],
    result_tasks: list[TaskWithIntents],
    orig_rows: dict[int, TaskRow],
) -> list[tuple[int, IntentDisposition]]:
    __list = intents
    if __list == []:
        return []
    r = __list[0]
    rest = __list[1:]
    rest_ = classify_rescope_intents(
        rest,
        result_tasks,
        orig_rows,
    )
    cid = r.intent_comment_id
    return [(cid, classify_intent(cid, result_tasks, orig_rows))] + rest_


def find_intent_row(
    intent: int,
    intents: list[IntentRow],
) -> IntentRow | None:
    for r in intents:
        if r.intent_comment_id == intent:
            return r
        continue
    return None


def find_intent_verdict(
    intent: int,
    verdicts: list[VerdictRow],
) -> VerdictRow | None:
    for v in verdicts:
        if v.verdict_intent_id == intent:
            return v
        continue
    return None


def has_earlier_attributed_sibling(
    intent: IntentRow,
    intents: list[IntentRow],
    dispositions: list[tuple[int, IntentDisposition]],
) -> bool:
    for other in intents:
        if other.intent_comment_id == intent.intent_comment_id:
            continue
        __option = find_disposition(other.intent_comment_id, dispositions)
        if __option is None:
            continue
        d = __option
        match d.disp_kind:
            case DispMaterial():
                if other.intent_index < intent.intent_index:
                    return True
                continue
            case DispAggregation():
                if other.intent_index < intent.intent_index:
                    return True
                continue
            case DispUnhandled():
                continue
            case __impossible:
                assert_never(__impossible)
    return False


def is_self_supersedence(
    verdict: VerdictRow,
    intent: IntentRow,
    intents: list[IntentRow],
) -> bool:
    __option = verdict.verdict_by_intent
    if __option is None:
        return False
    target = __option
    __option = find_intent_row(target, intents)
    if __option is None:
        return False
    by_intent = __option
    return intent.intent_author == by_intent.intent_author


def notify_decision_for(
    r: IntentRow,
    disposition: IntentDisposition,
    verdict: VerdictRow | None,
    intents: list[IntentRow],
    dispositions: list[tuple[int, IntentDisposition]],
) -> NotifyDecision:
    __option = verdict
    if __option is None:
        match disposition.disp_kind:
            case DispMaterial():
                return NotifyMaterial()
            case DispAggregation():
                return NotifySilent()
            case DispUnhandled():
                if has_earlier_attributed_sibling(r, intents, dispositions):
                    return NotifyUnhandled()
                return NotifySilent()
            case __impossible:
                assert_never(__impossible)
    v = __option
    if v.is_superseded():
        if is_self_supersedence(v, r, intents):
            return NotifySilent()
        return NotifyOverridden()
    match disposition.disp_kind:
        case DispMaterial():
            return NotifyMaterial()
        case DispAggregation():
            return NotifySilent()
        case DispUnhandled():
            if has_earlier_attributed_sibling(r, intents, dispositions):
                return NotifyUnhandled()
            return NotifySilent()
        case __impossible:
            assert_never(__impossible)


def disposition_or_unhandled(
    intent: int,
    dispositions: list[tuple[int, IntentDisposition]],
) -> IntentDisposition:
    __option = find_disposition(intent, dispositions)
    if __option is None:
        return IntentDisposition(
            disp_kind=DispUnhandled(),
            disp_affected=[],
        )
    d = __option
    return d


def reply_back_entry(
    intent: IntentRow,
    verdicts: list[VerdictRow],
    intents: list[IntentRow],
    dispositions: list[tuple[int, IntentDisposition]],
) -> tuple[int, NotifyDecision] | None:
    cid = intent.intent_comment_id
    decision = notify_decision_for(
        intent,
        disposition_or_unhandled(cid, dispositions),
        find_intent_verdict(cid, verdicts),
        intents,
        dispositions,
    )
    if isinstance(decision, NotifySilent):
        return None
    return (
        cid,
        decision,
    )


def reply_back_intents_in(
    cursor: list[IntentRow],
    intents: list[IntentRow],
    verdicts: list[VerdictRow],
    dispositions: list[tuple[int, IntentDisposition]],
) -> list[tuple[int, NotifyDecision]]:
    __list = cursor
    if __list == []:
        return []
    r = __list[0]
    rest = __list[1:]
    rest_ = reply_back_intents_in(
        rest,
        intents,
        verdicts,
        dispositions,
    )
    __option = reply_back_entry(r, verdicts, intents, dispositions)
    if __option is None:
        return rest_
    entry = __option
    return [entry] + rest_


def reply_back_intents(
    intents: list[IntentRow],
    verdicts: list[VerdictRow],
    dispositions: list[tuple[int, IntentDisposition]],
) -> list[tuple[int, NotifyDecision]]:
    return reply_back_intents_in(
        intents,
        intents,
        verdicts,
        dispositions,
    )
