(** Rocq → Python extraction backend.
    Phase 1: plugin skeleton — all nodes emit [# UNIMPL <Node>] stubs. *)

open Pp
open Names
open Miniml
open Common

(*s Keywords that may not be used as Python identifiers. *)

let keywords =
  let kws = [
    "False"; "None"; "True"; "and"; "as"; "assert"; "async"; "await";
    "break"; "class"; "continue"; "def"; "del"; "elif"; "else"; "except";
    "finally"; "for"; "from"; "global"; "if"; "import"; "in"; "is";
    "lambda"; "nonlocal"; "not"; "or"; "pass"; "raise"; "return"; "try";
    "while"; "with"; "yield";
    (* built-ins that clash in practice *)
    "type"; "list"; "dict"; "set"; "int"; "float"; "str"; "bool";
    "bytes"; "object"; "print"; "len"; "range"; "map"; "filter"; "zip";
  ] in
  List.fold_left (fun s w -> Id.Set.add (Id.of_string w) s) Id.Set.empty kws

(*s File naming: module path → base filename (no suffix). *)

let file_naming state mp =
  Table.file_of_modfile (State.get_table state) mp

(*s Preamble emitted at the top of every extracted .py file. *)

let preamble _state _name _comment _used_modules _safe =
  str "# Generated by rocq-python-extraction (Phase 1 skeleton)" ++ fnl () ++
  str "__ = None  # erased logical argument" ++ fnl ()

(*s Stub: emit [# UNIMPL <Variant>] for each ml_decl variant. *)

let pp_decl _state = function
  | Dind  _     -> str "# UNIMPL Dind"  ++ fnl ()
  | Dtype _     -> str "# UNIMPL Dtype" ++ fnl ()
  | Dterm _     -> str "# UNIMPL Dterm" ++ fnl ()
  | Dfix  _     -> str "# UNIMPL Dfix"  ++ fnl ()

(*s Stub: walk the ml_structure and emit per-element UNIMPL markers. *)

let pp_structure_elem state = function
  | (_, SEdecl d)    -> pp_decl state d
  | (_, SEmodule _)  -> str "# UNIMPL SEmodule"  ++ fnl ()
  | (_, SEmodtype _) -> str "# UNIMPL SEmodtype" ++ fnl ()

let pp_struct state struc =
  let pp_mod (_mp, sel) =
    prlist (pp_structure_elem state) sel
  in
  prlist pp_mod struc

(*s No interface file for Python. *)

let sig_preamble _state _name _comment _used_modules _safe = mt ()

let pp_sig _state _sig = mt ()

(*s The language descriptor record registered with the extraction framework. *)

let python_descr : Common.State.t language_descr = {
  keywords;
  file_suffix    = ".py";
  file_naming;
  preamble;
  pp_struct;
  sig_suffix     = None;
  sig_preamble;
  pp_sig;
  pp_decl;
}
