(** Rocq → Python extraction backend.
    Phase 2: expression printer — all [ml_ast] nodes except [MLfix]. *)

open Pp
open Names
open Miniml
open Mlutil
open Table
open Common

(*s Keywords that may not be used as Python identifiers. *)

let keywords =
  let kws = [
    "False"; "None"; "True"; "and"; "as"; "assert"; "async"; "await";
    "break"; "class"; "continue"; "def"; "del"; "elif"; "else"; "except";
    "finally"; "for"; "from"; "global"; "if"; "import"; "in"; "is";
    "lambda"; "nonlocal"; "not"; "or"; "pass"; "raise"; "return"; "try";
    "while"; "with"; "yield";
    (* built-ins that clash in practice *)
    "type"; "list"; "dict"; "set"; "int"; "float"; "str"; "bool";
    "bytes"; "object"; "print"; "len"; "range"; "map"; "filter"; "zip";
  ] in
  List.fold_left (fun s w -> Id.Set.add (Id.of_string w) s) Id.Set.empty kws

(*s File naming: module path → base filename (no suffix). *)

let file_naming state mp =
  file_of_modfile (State.get_table state) mp

(*s Preamble emitted at the top of every extracted .py file. *)

let preamble _state _name _comment _used_modules _safe =
  str "# Generated by rocq-python-extraction" ++ fnl () ++
  str "__ = None  # erased logical argument" ++ fnl ()

(*s Helpers for Python literal emission. *)

(** Escape a string for use in Python double-quoted string literals. *)
let py_escape_str s =
  let buf = Buffer.create (String.length s + 2) in
  String.iter (function
    | '"'  -> Buffer.add_string buf "\\\""
    | '\\' -> Buffer.add_string buf "\\\\"
    | '\n' -> Buffer.add_string buf "\\n"
    | '\r' -> Buffer.add_string buf "\\r"
    | '\t' -> Buffer.add_string buf "\\t"
    | c    -> Buffer.add_char buf c) s;
  Buffer.contents buf

(** Escape bytes for Python [b"..."] literals.  Non-printable and non-ASCII
    bytes are emitted as [\\xHH] hex escapes. *)
let py_escape_bytes s =
  let buf = Buffer.create (String.length s + 2) in
  String.iter (fun c ->
    let code = Char.code c in
    if code >= 32 && code < 127 && c <> '"' && c <> '\\' then
      Buffer.add_char buf c
    else
      Buffer.add_string buf (Printf.sprintf "\\x%02x" code)) s;
  Buffer.contents buf

(** Emit a Python float literal.  [Float64.to_string] uses ["nan"],
    ["infinity"], and ["neg_infinity"]; map these to Python's forms. *)
let pp_float_lit f =
  match Float64.to_string f with
  | "nan"          -> str "float('nan')"
  | "infinity"     -> str "float('inf')"
  | "neg_infinity" -> str "float('-inf')"
  | s              -> str s

(*s Global reference printer.  Honours [Extract Constant ... => "..."]
    inline-custom declarations. *)

let pp_glob state r =
  if is_inline_custom r then str (find_custom r)
  else str (pp_global state Term r)

(*s Helpers for [MLcons] emission. *)

(** Return the parent inductive reference for a constructor or inductive ref. *)
let get_ind r =
  let open GlobRef in
  match r.glob with
  | IndRef _              -> r
  | ConstructRef (ind, _) -> { glob = IndRef ind; inst = r.inst }
  | _                     -> assert false

(** KerName of an inductive reference (for record field key lookup). *)
let kn_of_ind r =
  let open GlobRef in
  match r.glob with
  | IndRef (kn, _) -> MutInd.user kn
  | _              -> assert false

(** Python keyword-argument name for record field at position [i].
    Uses [pp_global_with_key] for named fields, ["arg<i>"] for anonymous ones. *)
let pp_field_name state r fds i =
  match List.nth fds i with
  | Some r' -> str (pp_global_with_key state Term (kn_of_ind (get_ind r)) r')
  | None    -> str (Printf.sprintf "arg%d" i)

(** Raw constructor name for [r], accounting for inline-custom declarations. *)
let str_cons state r =
  if is_inline_custom r then find_custom r
  else pp_global state Cons r

(*s Pattern printer for Python [case] syntax. *)

(** Check whether pattern [p] has a custom extraction equal to string [s].
    Used to detect bool patterns mapped to ["True"] / ["False"]. *)
let is_bool_patt p s =
  try
    let r = match p with
      | Pusual r | Pcons (r, []) -> r
      | _ -> raise Not_found
    in
    String.equal (find_custom r) s
  with Not_found -> false

(** Pretty-print an [ml_pattern] in Python [case] syntax.
    [ids] are the branch binder names in source order (outermost first),
    already renamed and ready to emit.
    [env'] is the de Bruijn environment with those binders pushed. *)
let rec pp_pattern state ids env' = function
  | Pcons (r, []) ->
      let cons = str_cons state r in
      (* Erased / empty-name constructor: emit wildcard so the arm still matches *)
      if String.equal "" cons then str "_"
      else str cons ++ str "()"
  | Pcons (r, pats) ->
      str (str_cons state r) ++ str "(" ++
      prlist_with_sep (fun () -> str ", ") (pp_pattern state ids env') pats ++
      str ")"
  | Pusual r ->
      (* Shorthand for [Pcons(r,[Prel n;…;Prel 1])].  [ids] already holds the
         renamed binders in source order — emit them positionally. *)
      str (str_cons state r) ++ str "(" ++
      prlist_with_sep (fun () -> str ", ") Id.print ids ++
      str ")"
  | Ptuple pats ->
      str "(" ++
      prlist_with_sep (fun () -> str ", ") (pp_pattern state ids env') pats ++
      str ")"
  | Prel n ->
      Id.print (get_db_name n env')
  | Pwild ->
      str "_"

(*s Core expression printer.
    [env] carries de Bruijn binder names (innermost first). *)

let rec pp_expr state env = function
  | MLrel n ->
      (* De Bruijn variable: look up the binder name.  The dummy name [_]
         signals an erased binder; emit [__] (the module-level sentinel). *)
      let id = get_db_name n env in
      let id = if Id.equal id dummy_name then Id.of_string "__" else id in
      Id.print id
  | MLglob r ->
      pp_glob state r
  | MLdummy _ ->
      str "__"
  | MLexn s ->
      str "raise RuntimeError(\"" ++ str (py_escape_str s) ++ str "\")"
  | MLaxiom s ->
      str "raise NotImplementedError(\"AXIOM TO BE REALIZED: " ++
      str (py_escape_str s) ++ str "\")"
  | MLmagic a ->
      (* Identity coercion — Python is dynamically typed; emit inner expr. *)
      pp_expr state env a
  | MLuint i ->
      str (Uint63.to_string i)
  | MLfloat f ->
      pp_float_lit f
  | MLstring s ->
      str "b\"" ++ str (py_escape_bytes (Pstring.to_string s)) ++ str "\""
  | MLparray _ ->
      str "raise NotImplementedError(\"MLparray: persistent arrays not yet supported\")"
  | MLapp (f, args) ->
      (* Flatten left-associative curried application:
         MLapp(MLapp(f,[a]),[b]) → f(a, b) *)
      let rec collect acc = function
        | MLapp (g, more) -> collect (more @ acc) g
        | head            -> (head, acc)
      in
      let (head, all_args) = collect args f in
      (* Parenthesise the function if it is itself a lambda expression,
         since [lambda x: e] has very low precedence in Python. *)
      let pp_head =
        match head with
        | MLlam _ -> str "(" ++ pp_expr state env head ++ str ")"
        | _       -> pp_expr state env head
      in
      pp_head ++ str "(" ++
      prlist_with_sep (fun () -> str ", ") (pp_expr state env) all_args ++
      str ")"
  | MLlam _ as a ->
      (* Collect consecutive lambdas: MLlam(x, MLlam(y, body)) → lambda x, y: body.
         [collect_lams] returns ids innermost-first; reverse for Python source order. *)
      let ids, body = collect_lams a in
      let params = List.map id_of_mlid ids in
      let params, env' = push_vars params env in
      let pp_param id =
        (* Erased binders use [_] (Python's throwaway) in binder position. *)
        if Id.equal id dummy_name then str "_" else Id.print id
      in
      str "lambda " ++
      prlist_with_sep (fun () -> str ", ") pp_param (List.rev params) ++
      str ": " ++
      pp_expr state env' body
  | MLletin (id, a1, a2) ->
      (* Let binding in expression context: lambda-lift to [(lambda x: a2)(a1)].
         This is safe in pure functional code and avoids statement–expression
         impedance.  Statement-level [Dterm] will get a proper [def]/assignment
         form in the "Wire Dterm and Dfix" task. *)
      let params, env' = push_vars [id_of_mlid id] env in
      let bname = List.hd params in
      let pp_binder =
        if Id.equal bname dummy_name then str "_" else Id.print bname
      in
      str "(lambda " ++ pp_binder ++ str ": " ++
      pp_expr state env' a2 ++ str ")(" ++
      pp_expr state env a1 ++ str ")"
  | MLtuple l ->
      (* Tuple literal: (a, b, c) *)
      str "(" ++
      prlist_with_sep (fun () -> str ", ") (pp_expr state env) l ++
      str ")"
  | MLcons (_, r, args) ->
      let cons_name = str_cons state r in
      if is_coinductive (State.get_table state) r then
        (* Coinductive: wrap in a thunk so consumers can force lazily *)
        str "lambda: " ++
        ( if String.equal "" cons_name then
            (* erased coinductive constructor — unusual but valid *)
            (match args with [a] -> pp_expr state env a | _ -> assert false)
          else if List.is_empty args then str cons_name
          else
            str cons_name ++ str "(" ++
            prlist_with_sep (fun () -> str ", ") (pp_expr state env) args ++
            str ")" )
      else if String.equal "" cons_name then
        (* Singleton / newtype erasure — emit content directly *)
        ( match args with
          | []  -> str "None"
          | [a] -> pp_expr state env a
          | _   ->
              str "(" ++
              prlist_with_sep (fun () -> str ", ") (pp_expr state env) args ++
              str ")" )
      else
        let fds = get_record_fields (State.get_table state) r in
        if not (List.is_empty fds) then
          (* Record type: keyword arguments [T(field=a, field2=b)] *)
          str cons_name ++ str "(" ++
          prlist_with_sep (fun () -> str ", ")
            (fun (i, a) ->
               pp_field_name state r fds i ++ str "=" ++ pp_expr state env a)
            (List.mapi (fun i a -> (i, a)) args) ++
          str ")"
        else if List.is_empty args then
          str cons_name
        else
          (* Standard type: positional arguments [ConstrName(a, b)] *)
          str cons_name ++ str "(" ++
          prlist_with_sep (fun () -> str ", ") (pp_expr state env) args ++
          str ")"
  | MLcase (_, scrutinee, branches) ->
      (* Boolean match: [if cond then e1 else e2] → Python ternary [e1 if cond else e2].
         Detect the bool pattern by checking if the two arms are mapped to
         ["True"] and ["False"] via [Extract Inductive bool]. *)
      let is_bool =
        Array.length branches = 2 &&
        ( let (_, p0, _) = branches.(0) in
          let (_, p1, _) = branches.(1) in
          is_bool_patt p0 "True" && is_bool_patt p1 "False" )
      in
      if is_bool then
        let (_, _, body_true)  = branches.(0) in
        let (_, _, body_false) = branches.(1) in
        pp_expr state env body_true  ++ str " if " ++
        pp_expr state env scrutinee  ++ str " else " ++
        pp_expr state env body_false
      else
        (* General match: emit Python [match]/[case] statement.
           This is a statement in Python, so it only works correctly when the
           surrounding [Dterm] or [MLletin] emits it inside a function body.
           The "Wire Dterm and Dfix" task handles that lifting.  For now we
           emit the raw statement form so the structure is visible. *)
        let pp_branch (ids, pat, body) =
          (* [push_vars] wants ids innermost-first (de Bruijn order).
             [collect_lams]/branch ids come outermost-first, so reverse. *)
          let ids', env' = push_vars (List.rev_map id_of_mlid ids) env in
          (* After push, [ids'] are also innermost-first; re-reverse for
             source order so [pp_pattern] can emit positional names correctly. *)
          let pp_pat  = pp_pattern state (List.rev ids') env' pat in
          let pp_body = pp_expr state env' body in
          str "    case " ++ pp_pat ++ str ":" ++ fnl () ++
          str "        " ++ pp_body
        in
        str "match " ++ pp_expr state env scrutinee ++ str ":" ++ fnl () ++
        prlist_with_sep fnl pp_branch (Array.to_list branches)
  (* Stub — replaced in the MLfix task *)
  | MLfix   _ -> str "# UNIMPL MLfix"

(*s Declaration printer.  [Dterm] now emits real Python for the RHS
    expression (simple [name = expr] form).  Full lambda-aware wiring
    comes in the "Wire Dterm and Dfix" task. *)

let pp_decl state = function
  | Dind  _     -> str "# UNIMPL Dind"  ++ fnl ()
  | Dtype _     -> str "# UNIMPL Dtype" ++ fnl ()
  | Dterm (r, a, _) ->
      let env = empty_env state () in
      str (pp_global state Term r) ++ str " = " ++
      pp_expr state env a ++ fnl ()
  | Dfix  _     -> str "# UNIMPL Dfix"  ++ fnl ()

(*s Module structure walker.
    [State.with_visibility] must be called around each module so that
    [pp_global] can resolve names relative to the current module path. *)

let pp_structure_elem state = function
  | (_, SEdecl d)    -> pp_decl state d
  | (_, SEmodule _)  -> str "# UNIMPL SEmodule"  ++ fnl ()
  | (_, SEmodtype _) -> str "# UNIMPL SEmodtype" ++ fnl ()

let pp_struct state struc =
  let pp_mod (mp, sel) =
    State.with_visibility state mp [] (fun state ->
      prlist (pp_structure_elem state) sel)
  in
  prlist pp_mod struc

(*s No interface file for Python. *)

let sig_preamble _state _name _comment _used_modules _safe = mt ()

let pp_sig _state _sig = mt ()

(*s The language descriptor record registered with the extraction framework. *)

let python_descr : Common.State.t language_descr = {
  keywords;
  file_suffix    = ".py";
  file_naming;
  preamble;
  pp_struct;
  sig_suffix     = None;
  sig_preamble;
  pp_sig;
  pp_decl;
}
