lib: [
  "_build/install/default/lib/rocq-python-extraction/META"
  "_build/install/default/lib/rocq-python-extraction/dune-package"
  "_build/install/default/lib/rocq-python-extraction/g_python_extraction.ml"
  "_build/install/default/lib/rocq-python-extraction/opam"
  "_build/install/default/lib/rocq-python-extraction/python.ml"
  "_build/install/default/lib/rocq-python-extraction/rocq_python_extraction_plugin.a"
  "_build/install/default/lib/rocq-python-extraction/rocq_python_extraction_plugin.cma"
  "_build/install/default/lib/rocq-python-extraction/rocq_python_extraction_plugin.cmi"
  "_build/install/default/lib/rocq-python-extraction/rocq_python_extraction_plugin.cmt"
  "_build/install/default/lib/rocq-python-extraction/rocq_python_extraction_plugin.cmx"
  "_build/install/default/lib/rocq-python-extraction/rocq_python_extraction_plugin.cmxa"
  "_build/install/default/lib/rocq-python-extraction/rocq_python_extraction_plugin.ml"
  "_build/install/default/lib/rocq-python-extraction/rocq_python_extraction_plugin__G_python_extraction.cmi"
  "_build/install/default/lib/rocq-python-extraction/rocq_python_extraction_plugin__G_python_extraction.cmt"
  "_build/install/default/lib/rocq-python-extraction/rocq_python_extraction_plugin__G_python_extraction.cmx"
  "_build/install/default/lib/rocq-python-extraction/rocq_python_extraction_plugin__Python.cmi"
  "_build/install/default/lib/rocq-python-extraction/rocq_python_extraction_plugin__Python.cmt"
  "_build/install/default/lib/rocq-python-extraction/rocq_python_extraction_plugin__Python.cmx"
]
libexec: [
  "_build/install/default/lib/rocq-python-extraction/rocq_python_extraction_plugin.cmxs"
]
